### ISSUE TITLE
SIGABRT, terminate called after throwing an instance of 'SH4ThrownException'

### ISSUE THREAD

**Issue by Azelphur** [libretro/reicast-emulator#24]
Hi, been trying to get libretro-reicast working, but no luck. It crashes on startup. Here's the backtrace.

```
$ gdb retroarch
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from retroarch...(no debugging symbols found)...done.
(gdb) set args -f -f -L reicast_libretro.so ~/Emulation/Dreamcast/Power\ Stone\ 2.cdiQuit
(gdb) set args -f -L reicast_libretro.so ~/Emulation/Dreamcast/Power\ Stone\ 2.cdi
(gdb) run
Starting program: /usr/bin/retroarch -f -L reicast_libretro.so ~/Emulation/Dreamcast/Power\ Stone\ 2.cdi
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe35cf700 (LWP 2776)]
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: /home/emulationstation/.config/retroarch/retroarch.cfg.
[New Thread 0x7fffe2dce700 (LWP 2777)]
RetroArch [INFO] :: Loading dynamic libretro core from: "/home/emulationstation/reicast_libretro.so"
RetroArch [INFO] :: Overrides: no core-specific overrides found at /home/emulationstation/.config/retroarch/Reicast/Reicast.cfg
RetroArch [INFO] :: Overrides: no game-specific overrides found at /home/emulationstation/.config/retroarch/Reicast/Power Stone 2.cfg
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: core name: Reicast
RetroArch [INFO] :: Remaps: game name: Power Stone 2
RetroArch [INFO] :: Remaps: remap directory: /home/emulationstation/.config/retroarch/remap
RetroArch [INFO] :: Remaps: no game-specific remap found at /home/emulationstation/.config/retroarch/remap/Reicast/Power Stone 2.rmp
RetroArch [INFO] :: Remaps: no core-specific remap found at /home/emulationstation/.config/retroarch/remap/Reicast/Reicast.rmp
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Environ GET_PERF_INTERFACE.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: XRGB8888.
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] ::     RetroPad, User 1, Button "B (bottom)" => "A"
RetroArch [INFO] ::     RetroPad, User 1, Button "Y (left)" => "X"
RetroArch [INFO] ::     RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] ::     RetroPad, User 1, Button "A (right)" => "B"
RetroArch [INFO] ::     RetroPad, User 1, Button "X (up)" => "Y"
RetroArch [INFO] ::     RetroPad, User 1, Button "L" => "L (fierce)"
RetroArch [INFO] ::     RetroPad, User 1, Button "R" => "R (fierce)"
RetroArch [INFO] ::     RetroPad, User 1, Button "L2" => "L (weak)"
RetroArch [INFO] ::     RetroPad, User 1, Button "R2" => "R (weak)"
RetroArch [INFO] ::     RetroPad, User 2, Button "B (bottom)" => "A"
RetroArch [INFO] ::     RetroPad, User 2, Button "Y (left)" => "X"
RetroArch [INFO] ::     RetroPad, User 2, Button "Start" => "Start"
RetroArch [INFO] ::     RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] ::     RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] ::     RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] ::     RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] ::     RetroPad, User 2, Button "A (right)" => "B"
RetroArch [INFO] ::     RetroPad, User 2, Button "X (up)" => "Y"
RetroArch [INFO] ::     RetroPad, User 2, Button "L" => "L (fierce)"
RetroArch [INFO] ::     RetroPad, User 2, Button "R" => "R (fierce)"
RetroArch [INFO] ::     RetroPad, User 2, Button "L2" => "L (weak)"
RetroArch [INFO] ::     RetroPad, User 2, Button "R2" => "R (weak)"
RetroArch [INFO] ::     RetroPad, User 3, Button "B (bottom)" => "A"
RetroArch [INFO] ::     RetroPad, User 3, Button "Y (left)" => "X"
RetroArch [INFO] ::     RetroPad, User 3, Button "Start" => "Start"
RetroArch [INFO] ::     RetroPad, User 3, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] ::     RetroPad, User 3, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] ::     RetroPad, User 3, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] ::     RetroPad, User 3, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] ::     RetroPad, User 3, Button "A (right)" => "B"
RetroArch [INFO] ::     RetroPad, User 3, Button "X (up)" => "Y"
RetroArch [INFO] ::     RetroPad, User 3, Button "L" => "L (fierce)"
RetroArch [INFO] ::     RetroPad, User 3, Button "R" => "R (fierce)"
RetroArch [INFO] ::     RetroPad, User 3, Button "L2" => "L (weak)"
RetroArch [INFO] ::     RetroPad, User 3, Button "R2" => "R (weak)"
RetroArch [INFO] ::     RetroPad, User 4, Button "B (bottom)" => "A"
RetroArch [INFO] ::     RetroPad, User 4, Button "Y (left)" => "X"
RetroArch [INFO] ::     RetroPad, User 4, Button "Start" => "Start"
RetroArch [INFO] ::     RetroPad, User 4, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] ::     RetroPad, User 4, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] ::     RetroPad, User 4, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] ::     RetroPad, User 4, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] ::     RetroPad, User 4, Button "A (right)" => "B"
RetroArch [INFO] ::     RetroPad, User 4, Button "X (up)" => "Y"
RetroArch [INFO] ::     RetroPad, User 4, Button "L" => "L (fierce)"
RetroArch [INFO] ::     RetroPad, User 4, Button "R" => "R (fierce)"
RetroArch [INFO] ::     RetroPad, User 4, Button "L2" => "L (weak)"
RetroArch [INFO] ::     RetroPad, User 4, Button "R2" => "R (weak)"
RetroArch [INFO] :: Environ GET_RUMBLE_INTERFACE.
RetroArch [libretro INFO] :: Rumble interface supported!
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR /home/emulationstation/Emulation/Dreamcast/Power Stone 2.cdi
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "/home/emulationstation/Emulation/Dreamcast/".
RetroArch [INFO] :: Environ GET_VARIABLE reicast_internal_resolution:
RetroArch [INFO] ::     640x480
[reicast]: Got size: 640 x 480.
RetroArch [INFO] :: Environ GET_VARIABLE reicast_cpu_mode:
RetroArch [INFO] ::     dynamic_recompiler
RetroArch [INFO] :: Environ GET_VARIABLE reicast_boot_to_bios:
RetroArch [INFO] ::     disabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_mipmapping:
RetroArch [INFO] ::     enabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_widescreen_hack:
RetroArch [INFO] ::     disabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_audio_buffer_size:
RetroArch [INFO] ::     1024
RetroArch [INFO] :: Environ GET_VARIABLE reicast_cable_type:
RetroArch [INFO] ::     TV (VBS/Y+S/C)
RetroArch [INFO] :: Environ GET_VARIABLE reicast_broadcast:
RetroArch [INFO] ::     4
RetroArch [INFO] :: Environ GET_VARIABLE reicast_region:
RetroArch [INFO] ::     3
RetroArch [INFO] :: Environ GET_VARIABLE reicast_precompile_shaders:
RetroArch [INFO] ::     disabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_enable_rtt:
RetroArch [INFO] ::     enabled
RetroArch [INFO] :: Environ GET_VARIABLE reicast_enable_purupuru:
RetroArch [INFO] ::     enabled
RetroArch [INFO] :: Environ SET_HW_RENDER.
RetroArch [INFO] :: Requesting OpenGL context.
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 44063.25 Hz.
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: Using HW render, OpenGL driver forced.
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Found GL context: x
RetroArch [INFO] :: Detecting screen resolution 2880x1620.
RetroArch [INFO] :: [X11]: Xinerama version: 1.1.
RetroArch [INFO] :: [X11]: Xinerama screens: 1.
RetroArch [INFO] :: [GLX]: Using Xinerama on screen #0.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 2880, H = 1620.
RetroArch [INFO] :: [GLX]: Using windowed fullscreen.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Mobile .
RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 11.2.1.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => exists
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 2880x1620
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Not loading any shader.
RetroArch [INFO] :: [GL]: Using 1 textures.
RetroArch [INFO] :: [GL]: Loaded 0 program(s).
RetroArch [INFO] :: [GL]: Initializing HW render (1024 x 1024).
RetroArch [INFO] :: [GL]: Max texture size: 8192 px, renderbuffer size: 8192 px.
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => exists
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
context_reset.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[New Thread 0x7fffd87c6700 (LWP 2809)]
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 768 frames
RetroArch [INFO] :: ALSA: Buffer size: 3072 frames
RetroArch [INFO] :: ALSA: Can pause: yes.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: null: [/home/emulationstation/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: ABDF0000, aram: cbdf0000, vram: AFDF0000, ram: B7DF0000
Resetting mem
VA2: UnLockRegion
VA2: UnLockRegion
VA2: UnLockRegion
Mem alloc successful!RetroArch [libretro INFO] :: Unable to find bios in 
/home/emulationstation/Emulation/Dreamcast//dc/
Exiting...No nvmem loaded
reios: Init
Did not load bios, using reios
Using Recompiler
Sh4 Reset
recSh4 Init
@@      ngen_ResetBlocks()
Freeing fpcb

         CodeCache addr: 0x7fffe0a85000 | from: 0x7fffe0a85000 | addr here: 0x7fffe1a8604e

Session 1 has 1 track(s)
Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 302     LBA: 0       
Track position: 352800

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 307517  LBA: 11702   
Track position: 1413504
gdrom: Opened image "/home/emulationstation/Emulation/Dreamcast/Power Stone 2.cdi"
VA2: UnLockRegion
VA2: UnLockRegion
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
VA2: UnLockRegion
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES743C GD-ROM1/1  JUE     07BBA10 MK-51049  V1.00720000823        1ST_READ.BIN    CAPCOM'
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 743C GD-ROM1/1  
reios: Area symbols is: JUE     
reios: Peripherals is: 07BBA10 
reios: Product number is: MK-51049  
reios: Product version is: V1.007
reios: Release date is: 20000823        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: CAPCOM
reios: Software name is: POWERSTONE 2 USA - SELFBOOTING - KALISTO                   
reios: loading ip.bin from FAD: 11852
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 11875, len: 22528
Found 1ST_READ.BIN at 0000C3
filename len: 14
file LBA: 158293
file LEN: 3097497
Applying dynarec type hack.
Using Recompiler
Sh4 Reset
cntx // fpcb offset: -68157440 // pc offset: -184 // pc A0000000

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe1a866cb in bm_GetCode (addr=2684354560) at core/hw/sh4/dyna/blockmanager.cpp:86
86      core/hw/sh4/dyna/blockmanager.cpp: Permission denied.
(gdb) continue
Continuing.
Get MemPtr unsupported area : addr=0xA0000000
-----------------
REIOS: Booting up
-----------------

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe1a866cb in bm_GetCode (addr=2885714688) at core/hw/sh4/dyna/blockmanager.cpp:86
86      in core/hw/sh4/dyna/blockmanager.cpp
(gdb) continue
Continuing.
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC0082FE

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe1a866cb in bm_GetCode (addr=2885714688) at core/hw/sh4/dyna/blockmanager.cpp:86
86      in core/hw/sh4/dyna/blockmanager.cpp
(gdb) continue
Continuing.
iNimp FFFF
terminate called after throwing an instance of 'SH4ThrownException'

Thread 1 "retroarch" received signal SIGABRT, Aborted.
0x00007ffff00382a8 in raise () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff00382a8 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff003972a in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007fffe5f5c7cd in __gnu_cxx::__verbose_terminate_handler () at /build/gcc-multilib/src/gcc-5-20160209/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#3  0x00007fffe5f5a636 in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc-multilib/src/gcc-5-20160209/libstdc++-v3/libsupc++/eh_terminate.cc:47
No locals.
#4  0x00007fffe5f5a681 in std::terminate () at /build/gcc-multilib/src/gcc-5-20160209/libstdc++-v3/libsupc++/eh_terminate.cc:57
No locals.
#5  0x00007fffe5f5a898 in __cxxabiv1::__cxa_throw (obj=0x10208d0, tinfo=0x7fffe1d494a8 <typeinfo for SH4ThrownException>, dest=0x0) at /build/gcc-multilib/src/gcc-5-20160209/libstdc++-v3/libsupc++/eh_throw.cc:87
        globals = <optimized out>
#6  0x00007fffe057e209 in iNotImplemented (op=65535) at core/hw/sh4/interpr/sh4_opcodes.cpp:2218
        ex = {epc = 2885714688, expEvn = 384, callVect = 256}
#7  0x00007fffe05aef1e in opcode_ifb_pc::execute (this=0xf89ed0) at core/rec-cpp/rec_cpp.cpp:531
No locals.
#8  0x00007fffe060b688 in fnblock<3>::execute (this=0x102da90) at core/rec-cpp/rec_cpp.cpp:775
No locals.
#9  0x00007fffe06067bd in fnblock<3>::runner (fnb=0x102da90) at core/rec-cpp/rec_cpp.cpp:779
No locals.
#10 0x00007fffe05b7761 in disaptchn<0> () at core/rec-cpp/rec_cpp.cpp:1048
No locals.
#11 0x00007fffe0a7f644 in ngen_mainloop_exec (ctx=0x7fffa7cf0000) at core/rec.cpp:38
        rcb = 0x7fffe05b774a <disaptchn<0>()>
#12 0x00007fffe0a7f6a3 in ngen_mainloop (v_cntx=0x7fffabdf0000) at core/rec.cpp:56
        ctx = 0x7fffa7cf0000
#13 0x00007fffe1a85580 in recSh4_Run () at core/hw/sh4/dyna/driver.cpp:104
        __FUNCTION__ = "recSh4_Run"
#14 0x00007fffe0587d3b in dc_run () at core/nullDC.cpp:213
No locals.
#15 0x00007fffe1a94564 in co_dc_thread () at core/libretro/libretro.cpp:84
No locals.
#16 0x00007fffe1a989fe in co_swap () from /home/emulationstation/reicast_libretro.so
        co_active_buffer = {140737488342664, 0, 140736991113344, 140737488342924, 140737488347328, 0 <repeats 59 times>}
        co_active_handle = 0x7fffe0176010
#17 0x0000000000000000 in ?? ()
No symbol table info available.
```

Thanks.

**Comment by Azelphur** [comment]
Seems the BIOS files were in the wrong place, putting them in the right place resolves this.

**Comment by Alcaro** [comment]
I'd say there's still an issue. SIGABRT is the worst way to say "fix your BIOSes" I've ever seen.
