### ISSUE TITLE
Segmentation faults when using GDB

### ISSUE THREAD

**Issue by orbea** [libretro/reicast-emulator#28]
OS: `Slackware64-current`
`gdb-7.11-x86_64-1`
`RetroArch-1.3.2-x86_64-2_SBo`
`libretro-reicast-1cb37c6_2016.05.14_master-x86_64-1_git`

I was trying to run the reicast in GDB to examine some Mesa: User Errors and found that it segmentation faults, but only when run with GDB.
```
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from retroarch...(no debugging symbols found)...done.
(gdb) run -L reicast_libretro.so "/home/orbea/games/roms/dreamcast/Soul Calibur.cdi"
Starting program: /usr/bin/retroarch -L reicast_libretro.so "/home/orbea/games/roms/dreamcast/Soul Calibur.cdi"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffeaf25700 (LWP 24862)]
[New Thread 0x7fffea724700 (LWP 24863)]
[reicast]: Got size: 640 x 480.
context_reset.
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: C4D90000, aram: e4d90000, vram: C8D90000, ram: D0D90000
Resetting mem
Mem alloc successful!Loaded /home/orbea/games/bios/dc/dc_boot.bin as bootrom

Loaded /home/orbea/games/bios/dc/dc_flash.bin as nvram

Using Recompiler
Sh4 Reset
recSh4 Init
@@	ngen_ResetBlocks()
Freeing fpcb

	 CodeCache addr: 0x7fffe8406000 | from: 0x7fffe8406000 | addr here: 0x7fffe84059b0

Session 1 has 1 track(s)
Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 300     LBA: 0       
Track position: 352800

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 346001  LBA: 11700   
Track position: 1408800
gdrom: Opened image "/home/orbea/games/roms/dreamcast/Soul Calibur.cdi"
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES70B8 GD-ROM1/1  JUE     0799800 MK0815    V1.99920000623        1ST_READ.BIN    ECHELON         UTOPIA PRESENTS: SOULCALIBUR *FULL RIP*                                                                                         	'
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 70B8 GD-ROM1/1  
reios: Area symbols is: JUE     
reios: Peripherals is: 0799800 
reios: Product number is: MK0815    
reios: Product version is: V1.999
reios: Release date is: 20000623        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: ECHELON         
reios: Software name is: UTOPIA PRESENTS: SOULCALIBUR *FULL RIP*                                                                                         
reios: loading ip.bin from FAD: 11850
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 11873, len: 6144
Found 1ST_READ.BIN at 0000C3
filename len: 14
file LBA: 120336
file LEN: 4136960
Applying zmax hack.
cntx // fpcb offset: -68157440 // pc offset: -184 // pc A0000000

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe9406c22 in bm_GetCode(unsigned int) ()
   from /media/data/home/gittings/installed/libretro/tmp/libretro-reicast/reicast_libretro.so
(gdb) bt full
#0  0x00007fffe9406c22 in bm_GetCode(unsigned int) ()
   from /media/data/home/gittings/installed/libretro/tmp/libretro-reicast/reicast_libretro.so
No symbol table info available.
#1  0x00007fffe840199b in ngen_mainloop ()
   from /media/data/home/gittings/installed/libretro/tmp/libretro-reicast/reicast_libretro.so
No symbol table info available.
#2  0x00007fffe840599c in recSh4_Run() ()
   from /media/data/home/gittings/installed/libretro/tmp/libretro-reicast/reicast_libretro.so
No symbol table info available.
#3  0x00007fffe940f3b0 in co_swap ()
   from /media/data/home/gittings/installed/libretro/tmp/libretro-reicast/reicast_libretro.so
No symbol table info available.
#4  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by Alcaro** [comment]
The JIT catches and handles segfaults. Nothing we can do about it.

Workaround: (gdb) handle SIGSEGV nostop noprint

**Comment by orbea** [comment]
Thanks that works!
