### ISSUE TITLE
RetroArch crashes in Windows starting a game with Reicast

### ISSUE THREAD

**Issue by lollo78** [libretro/reicast-emulator#39]
Hi guys, how are you? ;)
From a couple of days, Reicast stopped working on Windows. It crashes RA if I try to load a game.
I'm using the latest nighlty build of RA for x86_x64 and Reicast .dll took from buildbot.
See you soon, bye!

**Comment by orbea** [comment]
Any chance you can git bisect this?

**Comment by lollo78** [comment]
Sorry, on Windows I don't compile RA: I use only the buildbot nightly.
If there's a way to download the old compiled .dll from buildbot (or other Website) I can test it.

**Comment by mac1202** [comment]
This seems to be the same issue as https://github.com/libretro/reicast-emulator/issues/40 posted bisect there.

**Comment by Tatsuya79** [comment]
I got this too on win7 x64:
```
vmem reserve: base: 13950000, aram: 33950000, vram: 17950000, ram: 1F950000
Resetting mem
Mem alloc successful!Loaded E:\Emulateurs\RetroArch64\system\dc\dc_boot.bin as b
ootrom

Loaded E:\Emulateurs\RetroArch64\system\dc\dc_nvmem.bin as nvram

Using Recompiler
Sh4 Reset
recSh4 Init
@@      ngen_ResetBlocks()
Freeing fpcb

Session 1 has 1 track(s)
Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 300     LBA: 0
Track position: 352800

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 315474  LBA: 11700
Track position: 1408800
gdrom: Opened image "E:\Roms\Sega - Dreamcast\Capcom vs SNK 2.cdi"
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES2698 GD-ROM1/1  JUE     27BBA1
0 T1249M    V1.00120010731        1ST_READ.BIN    ECHELON         CAPCOM VS SNK2

'                                 +Òý
reios: Hardware ID is: SEGA SEGAKATANA
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 2698 GD-ROM1/1
reios: Area symbols is: JUE
reios: Peripherals is: 27BBA10
reios: Product number is: T1249M
reios: Product version is: V1.001
reios: Release date is: 20010731
reios: Boot filename is: 1ST_READ.BIN
reios: Software company is: ECHELON
reios: Software name is: CAPCOM VS SNK2

reios: loading ip.bin from FAD: 11850
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 11873, len: 30720
Found 1ST_READ.BIN at 0000BB
filename len: 14
file LBA: 219194
file LEN: 2387249
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Sh4: i-cache invalidation A0000016
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at A0000016
Get MemPtr unsupported area : addr=0x80000080
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C0000DE
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
SPI : unknown ? [0x70]
SPI : unknown ? [0x71]
sh4io: Invalid read access @@ 00000030
Sh4: i-cache invalidation 8C00DD78
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
Sh4: i-cache invalidation 8C09E6A6
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
new tactx
new tactx
HASH: 8C09ED16 reloc >:1:05:BD3BE51F:1E886EE6:6BDB3F70:7FB25EA3:DE0083A8
HASH: 8C0BA526 reloc >:1:04:CB0C9B99:5082FB07:50A46C46:4035B1F1:6A9F47DC
HASH: 8C0BA506 reloc >:1:04:26AEABE5:E9D01A08:C25DD887:EEAFF173:CE2BBA10
HASH: 8C0BA50E reloc >:1:0A:5785DC3D:68688650:C5E1AFB3:7F686AE5:89538042
[GPF]Unhandled access to : 0x0
```

**Comment by godzil21** [comment]
same problem, reicast crashes trying to boot any game, same error message as above...

**Comment by lollo78** [comment]
On Windows, last reicast_libretro.dll (25-10-2016 04:01) on https://buildbot.libretro.com/nightly/windows/x86_64/latest/
solve the issue. At least for me.

**Comment by godzil21** [comment]
Hello lollo78!

Nope! Same crash...I have just tested it in 2 different rigs with the last core you appointed and Retroarch crashes when loading the game, curiously the boot screen loads ok, but if you put a game , cdi , gdi crashes inmediately with the mem error dumped above.

Thanks anyways.

**Comment by lollo78** [comment]
Try also with the latest RA

**Comment by godzil21** [comment]
Tested with the latest RA same problem , same crash. 

Regards!

**Comment by Tatsuya79** [comment]
No, still crashes the exact same way in win7 x64.
I tried with the newest nightly, removing every cfg, vmu_save and core options.

**Comment by twinaphex** [comment]
If it says 'reios' as it states in that log, then you're doing it wrong, it is defaulting then to the builtin HLE BIOS, and that only runs like maybe 15% of all games, and that is an optimistic figure.

You need it to detect your real BIOS.

**Comment by Tatsuya79** [comment]
I don't see how I could do it right. Both bios files are recognized, I verified their CRC.

I can boot into the bios if I have reicast_boot_to_bios = "enabled" but I can not launch my game from there. 
I don't see any other option to choose HLE or something else?
It always says "reios" whatever I do.

**Comment by Tatsuya79** [comment]
The older reicast core I use that works says reios too.

**Comment by twinaphex** [comment]
If it says reios then you don't have your BIOS files placed in the right directories and it can't find it, therefore it defaults to reios.

There can be no debate on this. It simply is. Sort it out on your end, but this is not a bug.

**Comment by anon35665567** [comment]
If RA is crashing due to missing bios files that is a bug. RA should not crash due to a core. SP is such an incompetent hack.

**Comment by fr500** [comment]
Here is the backtrace in case anyone can debug it

`Thread 1 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 18100.0x2214]
0x0000000016918330 in recSh4_Run() ()
   from D:\GameData\Emulators\RetroArch\libretro\reicast_libretro.dll
(gdb) bt full
#0  0x0000000016918330 in recSh4_Run() ()
   from D:\GameData\Emulators\RetroArch\libretro\reicast_libretro.dll
No symbol table info available.
#1  0x000000001691ce76 in retro_run ()
   from D:\GameData\Emulators\RetroArch\libretro\reicast_libretro.dll
No symbol table info available.
#2  0x0000000000402748 in core_run () at core_impl.c:407
No locals.
#3  0x0000000000412dd8 in runloop_iterate (sleep_ms=sleep_ms@entry=0x41bfde0)
    at runloop.c:1233
        i = <optimized out>
        current = <optimized out>
        target = <optimized out>
        to_sleep_ms = <optimized out>
        last_input = 256
        runloop_status = RUNLOOP_STATE_ITERATE
        frame_limit_minimum_time = 3333
        frame_limit_last_time = 319418512878
        settings = 0x80fe040
        current_input = <optimized out>
        old_input = 0
#4  0x00000000004016d0 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:127
        sleep_ms = 0
        ret = <optimized out>
        args = 0x0
        argc = <optimized out>
        argv = <optimized out>
        data = 0x0
        args = 0x0
#5  0x0000000000661fc8 in WinMain ()
No symbol table info available.
#6  0x00000000004013ed in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
        lock_free = <optimized out>
        fiberid = <optimized out>
        nested = <optimized out>
        lpszCommandLine = <optimized out>
        StartupInfo = {cb = 104, lpReserved = 0x439eeb0 "",
          lpDesktop = 0x439ee90 "",
          lpTitle = 0x4399250 "D:\\GameData\\Emulators\\RetroArch\\retroarch.exe", dwX = 0, dwY = 0, dwXSize = 0, dwYSize = 0,
          dwXCountChars = 0, dwYCountChars = 0, dwFillAttribute = 0,
          dwFlags = 0, wShowWindow = 0, cbReserved2 = 0, lpReserved2 = 0x0,
          hStdInput = 0xffffffffffffffff, hStdOutput = 0xffffffffffffffff,
          hStdError = 0xffffffffffffffff}
        inDoubleQuote = <optimized out>
#7  0x00000000004014fb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
        ret = 255
(gdb)
`

**Comment by Tatsuya79** [comment]
[Last commit](https://github.com/libretro/reicast-emulator/commit/3601150d1486912d5a9939edfa89ec7c7bd94351) didn't help, same crash.

**Comment by twinaphex** [comment]
radius says the problems started here for Windows  -

https://github.com/libretro/reicast-emulator/commit/366c8d0d77118abd0add52092aa3a00fa6038d60

I don't use Windows and I don't see anything obvious in this commit that could cause it to no longer work (but only for Windows). Maybe you can figure out how to get it to work again.

**Comment by Enverex** [comment]
Don't think it's fixed. Just recompiled RetroArch and Reicast from GIT and still ran into the issue:

```
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
new tactx
new tactx
SIGSEGV @ 0x41f12e67 (fault_handler+0x0xffff807e76d1d2b7) ... (nil) -> was not in vram
RetroArch [libretro INFO] :: Fatal error : segfault
 in fault_handler -> core/libretro/common.cpp : 346
DEBUGBREAK!
```

**Comment by godzil21** [comment]
FYI...In my windows10 system ( i7 without any graphics card) it works perfect without any problem...

**Comment by Tatsuya79** [comment]
http://libretro.com/forums/showthread.php?t=7387&p=50361#post50361
It seems to be an Nvidia specific issue, be it win10 or win7.

**Comment by mac1202** [comment]
Can someone can compile reicast prior to this commit 91d8bb04628569ec555e4c502e06ec65ca5aacbe to see if it s the same issue as https://github.com/libretro/reicast-emulator/issues/40

**Comment by fr500** [comment]
That commit is one commit after the one that broke windows so it's pointless to do any further testing
