### ISSUE TITLE
RetroArch crashes in Linux starting a game with 

### ISSUE THREAD

**Issue by Vochatrak** [libretro/reicast-emulator#40]
Good afternoon. 
When you run reicast-libretro any game crashes with this error:
$ retroarch
[reicast]: Got size: 640 x 480.
Creating dir: /home/dna/.config/retroarch/system/dc/data
context_reset.
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 5B5F0000, aram: 7b5f0000, vram: 5F5F0000, ram: 675F0000
Resetting mem
Mem alloc successful!Loaded /home/dna/.config/retroarch/system/dc/dc_boot.bin as bootrom

Loaded /home/dna/.config/retroarch/system/dc/dc_nvmem.bin as nvram

Using Recompiler
Sh4 Reset
recSh4 Init
@@      ngen_ResetBlocks()
Freeing fpcb

         CodeCache addr: 0x7f598b346000 | from: 0x7f598b346000 | addr here: 0x7f598b344750

Session 1 has 1 track(s)
Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 300     LBA: 0       
Track position: 352800

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 308004  LBA: 11700   
Track position: 1408800
gdrom: Opened image "/home/dna/build/Dragon.cdi"
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Initialising empty vmu...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISESA35C GD-ROM1/1  JUE     0619810 T17720N   V1.00220010703        1ST_READ.BIN    SEGA LC-T-177   DRAGONRIDERS - THE CHRONICLES OF PERN                                                                                           '
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: A35C GD-ROM1/1  
reios: Area symbols is: JUE     
reios: Peripherals is: 0619810 
reios: Product number is: T17720N   
reios: Product version is: V1.002
reios: Release date is: 20010703        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: SEGA LC-T-177   
reios: Software name is: DRAGONRIDERS - THE CHRONICLES OF PERN                                                                                           
reios: loading ip.bin from FAD: 11850
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 11877, len: 2048
Found 1ST_READ.BIN at 000093
filename len: 14
file LBA: 12041
file LEN: 1140092
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Sh4: i-cache invalidation A0000016
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at A0000016
Get MemPtr unsupported area : addr=0x80000080
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C0000DE
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
SPI : unknown ? [0x70]
SPI : unknown ? [0x71]
sh4io: Invalid read access @@ 00000030
Sh4: i-cache invalidation 8C00DD78
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C00DD78
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
G2-EXT1 DMA : SB_E1DIR==0:DMA Write to 0x9F0000 from 0xCFF0000 32 bytes
Sh4: i-cache invalidation 8C09E6A6
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at 8C09E6A6
Sh4: i-cache invalidation AC09D990
@@      ngen_ResetBlocks()
Freeing fpcb
recSh4:Dynarec Cache clear at AC09D990
new tactx
new tactx
SIGSEGV @ 0x4076ed67 (fault_handler+0x0xffff80a6b4421707) ... (nil) -> was not in vram
DEBUGBREAK!

OS - Rosa Linux R8 x64
Version Retroarch - v1.3.6
Libretro - courent nigtly build (and other 2 build from https://buildbot.libretro.com/nightly/linux/x86_64/ )

**Comment by mac1202** [comment]
I confirm this just compiled the latest git and got the same crash.

**Comment by mac1202** [comment]
Just did a git bisect, here s the result : 
`91d8bb04628569ec555e4c502e06ec65ca5aacbe is the first bad commit
commit 91d8bb04628569ec555e4c502e06ec65ca5aacbe
Author: twinaphex <libretro@gmail.com>
Date:   Mon Oct 17 20:55:51 2016 +0200

    Can toggle internal resolution now at runtime - still need to
    do AV info call

:040000 040000 812865e4e5430e3f86e37b644bfaacccdbbebf23 1faa6dd47c2bd2d5199b23bf5f2b4854bb5932ad M      core
`

**Comment by legluondunet** [comment]
Same bug for me, Retroarch Reicast core crashes for all Dreamcast game I tried to launch.
Debug terminal log here:

http://pastebin.com/eXnY6E70

**Comment by Enverex** [comment]
Backtrace for reference.

	reios: Boot filename is: 1ST_READ.BIN
	reios: Software company is: SEGA ENTERPRISES
	reios: Software name is: DAYTONAUSA
	reios: loading ip.bin from FAD: 45150
	reios: bootfile is '1ST_READ.BIN    '
	reios: iso9660 PVD found
	reios: iso9660 root_directory, FAD: 45170, len: 28672
	Found 1ST_READ.BIN at 000093
	filename len: 14
	file LBA: 548018
	file LEN: 2010720

	Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
	0x00007fffd3448989 in recSh4_Run() () from /usr/lib/libretro/reicast_libretro.so
	(gdb) bt
	#0  0x00007fffd3448989 in recSh4_Run() () from /usr/lib/libretro/reicast_libretro.so
	#1  0x00007fffd4451542 in retro_run () from /usr/lib/libretro/reicast_libretro.so
	#2  0x0000555555595927 in core_run () at core_impl.c:411
	#3  0x00005555555a722d in runloop_iterate (sleep_ms=0x7fffffffe60c) at runloop.c:1233
	#4  0x00005555555946e0 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:127
	#5  0x00007fffefee4291 in __libc_start_main () from /usr/lib/libc.so.6
	#6  0x000055555559170a in _start ()

**Comment by mudlord** [comment]
You answered your own question. The x64 "dynarec" is the spawn of Satan and buggy as heck.
